version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"  ## should keep this same as python environment for CLEDBenv

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
#  builder: html
#  fail_on_warning: false

# Explicitly set the version of Python and its requirements
python:
  install:    
    - requirements: docs/requirements.txt
    - method: pip
        path: .