## This is the configuration file
## for the readthedocs builder that is cross-linked to git updates
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"  ## should keep this same as python environment for CLEDBenv

## Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

## Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt

##
formats: all
# - epub
# - pdf