name: Publish to PyPI

on:
  push:
    tags:
      - 'disable*'  # Only run on tags like v1.0.0, v0.1, etc. ##currently disabled

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Needed for trusted publishing (if used)

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build tools
        run: |
          python -m pip install --upgrade build twine

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/* -u __token__