name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup-conda-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Latest version of the checkout action

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3  # Use the miniconda setup action
      with:
        miniconda-version: "latest"
        auto-activate-base: false

    - name: Install Conda dependencies
      shell: bash -l {0}  # Important: login shell to load conda
      run: |
        conda create --name CLEDBenv python=3.13
        conda init
        conda activate CLEDBenv
        conda install numpy=2.1 numba=0.61 scipy=1.15 astropy=7.0 pytest ipython tqdm

    - name: Run tests
      shell: bash -l {0}  # Important: login shell to load conda
      run: |
        conda init
        conda activate CLEDBenv
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest ./tests/  # Runs your tests with pytest
